var id = "NOOOOOOOO";
var name = "NOOOOOOOOOOOOO";
var description = "NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
var authors = "NOOOOOOOOOOOOOOOOOOOOO";
var version = 1;

game.f = BigNumber.from("ee100000");
